### PR TITLE
4.0.x merge pull request #51

### PR DESCRIPTION
**Pull request by CodingParsley**

### CODE REVIEW

**Comment by ewencp** [comment]
Something seems off with the downstream dependency checks. It looks like for some reason it's extracting garbage for the version, which then makes the request to the dependency service fail. https://jenkins.confluent.io/job/confluentinc-pr/job/support-metrics-common/job/PR-53/2/execution/node/125/log/ I tried to reproduce locally but it seems to give valid output -- @xli1996 have you seen anything like this before? I don't think logs currently give enough info to track down, we can probably do some jenkins replays to track down if it's not a known issue.

**Comment by xli1996** [comment]
No it is not a known issue, quick look suggest the issue is `curl -f https://dependency-mgmt.tools.confluent-internal.io/v1/downstream_repos/support-metrics-common/[ERROR]` something was worng with the way it fetched maven version
`mvn help:evaluate -Dexpression=project.version -q -DforceStdout | tail -1`

**Comment by xli1996** [comment]
I think the issue is that oracle7-build-image which is the image use for 4.0.x job has a very old maven version which does not support `help` plugin. Maybe we can update the maven version for those images are just disable downstream changes there.

**Comment by xli1996** [comment]
I think it might because of the java version, though the document suggest it has support start from jdk 1.7, but it failed on `oracle7-build-image` which is what the build current use.

**Pull request closed without merging**
