### PR TITLE
[METRICS-1812] Remove 3.3.x Jenkinsfile

### PR DESCRIPTION
**Pull request by CodingParsley**
Remove jenkins job due to deprecation

### CODE REVIEW

**Comment by ijuma** [comment]
We can only remove this from the branches for which it exists in ce-kafka, right?

**Comment by CodingParsley** [comment]
> We can only remove this from the branches for which it exists in ce-kafka, right?

@ijuma Sorry for the delay... I somehow didn't get notification for the reply. I believe we don’t need to support 3.3.x as of August 1st so it should be safe to remove the job.

**Comment by ijuma** [comment]
@CodingParsley That's true. However, we must still support 4.0.x and newer versions. Are you going to ensure we don't remove it for newer branches when you `pint merge`?

**Comment by CodingParsley** [comment]
> @CodingParsley That's true. However, we must still support 4.0.x and newer versions. Are you going to ensure we don't remove it for newer branches when you `pint merge`?

@sirianni Do we have plans for that?

**Comment by sirianni** [comment]
> > @CodingParsley That's true. However, we must still support 4.0.x and newer versions. Are you going to ensure we don't remove it for newer branches when you `pint merge`?
> 
> @sirianni Do we have plans for that?

I'm not familiar with `pint merge`, but I believe the script propagates commits to other branches.   I think @ijuma 's request is for you to make sure that when you do this, you **don't** delete the `Jenkinsfile` in those branches.  

If this change is not to be propagated, then is there a need to run `pint merge` at all?

**Comment by ijuma** [comment]
We have a check for CI jobs that fails if `pint merge` is not run for projects where the policy is to commit to the oldest branch and then merge the changes to newer branches. In addition, I think we want to remove this file from 5.4 onwards too (support-metrics-common was moved to confluentinc/kafka at that point).

**Comment by sirianni** [comment]
> We have a check for CI jobs that fails if `pint merge` is not run for projects

OK thanks.  @CodingParsley , as @ijuma requests, when you run `pint merge` can you ensure that:
* The `Jenkinsfile` is not removed for branches earlier than 5.4
* The `Jenkinsfile` is removed from 5.4 onwards

?

Thanks.

**Comment by CodingParsley** [comment]
> > We have a check for CI jobs that fails if `pint merge` is not run for projects
> 
> OK thanks. @CodingParsley , as @ijuma requests, when you run `pint merge` can you ensure that:
> 
> * The `Jenkinsfile` is not removed for branches:  `4.0x <= branch < 5.4`
> * The `Jenkinsfile` is removed for branches >= 5.4
> 
> ?
> 
> Thanks.

Hi @ijuma I ran `pint merge` from branch 4.0x <= branch < 5.4 locally after the change and it does not seem to remove jenkinsfile for those branches. I wonder if it would be safe to say that the file wouldn't be removed after i merge the change?  Sorry I'm familiar with the CI jobs that would run for this repo...

**Comment by CodingParsley** [comment]
> > > We have a check for CI jobs that fails if `pint merge` is not run for projects
> > 
> > 
> > OK thanks. @CodingParsley , as @ijuma requests, when you run `pint merge` can you ensure that:
> > 
> > * The `Jenkinsfile` is not removed for branches:  `4.0x <= branch < 5.4`
> > * The `Jenkinsfile` is removed for branches >= 5.4
> > 
> > ?
> > Thanks.
> 
> Hi @ijuma I ran `pint merge` from branch 4.0x <= branch < 5.4 locally after the change and it does not seem to remove jenkinsfile for those branches. I wonder if it would be safe to say that the file wouldn't be removed after i merge the change? Sorry I'm not familiar with the CI jobs that would run for this repo...

@ijuma Just want to follow up on this!

**Comment by ijuma** [comment]
@CodingParsley You have to merge this first and then run `pint merge`.

**Comment by CodingParsley** [comment]
> @CodingParsley You have to merge this first and then run `pint merge`.

Ok can you give a +1 for the PR?

**Comment by ewencp** [comment]
You won't want to use pint merge, it doesn't have controls like this currently. Or at least you'd only want to use it for part of the merge.

You should merge this, then manually merge 3.3.x -> 4.0.x with `-s ours` so 4.0.x doesn't get the changes. From there you can pint merge.

I don't think need to do anything else since we already capped the versions for the repo, so there aren't any newer branches after 5.2.x (the move happened in 5.3.x, not 5.4.x).

**Comment by CodingParsley** [comment]
> then manually merge 3.3.x -> 4.0.x with `-s ours` so 4.0.x doesn't get the changes

I'm not sure which command with `-s ours` I should run and where I should run it . Could you explain it to me? Thanks!

**Comment by ewencp** [comment]
It's a parameter to `git merge`, when you are merging 3.3.x into 4.0.x

**Comment by CodingParsley** [comment]
Update: I don't see the change propagated into 4.0.x so there's nothing to be merged for 4.0.x.

**Comment by ewencp** [comment]
@CodingParsley merging isn't automated (and can't be fully anyway, in the case of conflicts). This is the reason `pint merge` exists -- it helps you do most merging automatically (when it merges cleanly), but will bail and leave you to resolve things if there are conflicts.

Confluent projects maintain multiple release versions, which are tracked on branches (e.g. 3.3.x, 4.0.x, ...). The `.x` part indicates it's a development version. When we need to do a release we create a tag from the current state of the branch. So 3.3.0, 3.3.1, 3.3.2, etc are created off the 3.3.x branch, each taking a newer version. But in parallel we are doing 4.0 releases against the 4.0.x branch. So, for example, 3.3.2 might be released *after* 4.0.0, since we're in maintenance mode for the 3.3.x branch.

In order to make sure bug fixes make their way to *all* newer releases they should, fixes are generally made to the *oldest* branch that is still supported and affected by the issue. We then merge the change through newer versions. So basically, pint merge is tooling that helps ensure everything that's in 3.3.x is in 4.0.x, 4.1.x, and everything newer. But pint merge is something devs need to run to ensure conflicts are resolved -- CI just fails builds if things aren't merged as a sanity check.

This is a weird case because removing the Jenkinsfile is something we want for only this branch -- 99% of cases we just want all changes in an older branch to be in all newer branches as well.

You still need to follow the merge process for this. The rough list would be:

* Merge (done)
* Make sure your repo is up to date (git fetch)
* Checkout 4.0.x, make sure up to date and clean, `git merge -s ours origin/3.3.x` (this is the case where you need `-s ours` since you don't want to propagate changes from 3.3.x)
* Now you can just run `pint merge` since there should be no real changes on newer branches anymore (we ignored them in the previous step) but to satisfy git history we still need to do the merge.

**Pull request merged**
